[fedora]
image=registry.fedoraproject.org/fedora-toolbox:38
pre_init_hooks=dnf -y install dnf-plugins-core && dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
additional_packages=git vim tmux helm terraform
init=false
pull=true
root=false
replace=true
start_now=true

[ubuntu]
image=quay.io/toolbx-images/ubuntu-toolbox:22.04
additional_packages=git vim tmux
init=false
pull=true
root=false
replace=true
start_now=false

[archlinux]
image=quay.io/toolbx-images/archlinux-toolbox
additional_packages=git vim tmux
init=false
pull=true
root=false
replace=true
start_now=false

; [debian]
; image=quay.io/toolbx-images/debian-toolbox:11 
; additional_packages=git vim tmux
; init=false
; pull=true
; root=false
; replace=true
; start_now=false

; [alpine]
; image=quay.io/toolbx-images/alpine-toolbox:3.17
; additional_packages=git vim tmux
; init=false
; pull=true
; root=false
; replace=true
; start_now=false

; [rockylinux]
; image=quay.io/toolbx-images/rockylinux-toolbox:9
; additional_packages=git vim tmux
; init=false
; pull=true
; root=false
; replace=true
; start_now=false
