# image will be published to ghcr.io/<user>/<name>
name: carbonite
# description will be included in the image's metadata
description: An evolving immutable Linux image for cloud software development.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      # Base packages
      - epiphany
      - libratbag-ratbagd
      - tailscale
      - wireguard-tools
      # Docker packages
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose # Deprecated, but some projects/tools still rely on it
      - docker-compose-plugin
      # Customisation
      - neovim
      - starship
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.discordapp.Discord
        - com.github.tchx84.Flatseal
        - com.mattermost.Desktop
        - com.mattjakeman.ExtensionManager
        - com.slack.Slack
        - com.spotify.Client
        - com.teamspeak.TeamSpeak
        - com.valvesoftware.Steam
        - im.riot.Riot
        - io.podman_desktop.PodmanDesktop
        - org.gnome.Boxes
        - org.gnome.Totem
        - org.mozilla.Thunderbird
        - org.mozilla.firefox
        - org.remmina.Remmina
        - org.telegram.desktop
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

  - type: script
    scripts:
      # set up the proper policy & signing files for signed images to work
      - signing.sh
      # configure systemd services
      - systemd-enable-services.sh
      - update-systemd-timeouts.sh
